openapi: 3.0.0

info:
  title: API для интеграции с ботом судей
  version: 2.0.0
  description: |

    ## Принципы работы

    1) API `divisions` отдает филиалы
    2) API `disicplines` отдает спортивные дисциплины. На стороне чат бота происходит мапинг дисциплин
    * индивидуальные дисциплины (`isTeam = false`) содержат одно соревнование (`competition`)
    * командные дисциплины (`isTeam = true`) содержат турнирную сетку (`stages`) с соревнованиями
    3) API `athletes` отдает список спортсменов с их дисциплинами и командами
    4) API `results` принимает результаты конкретного соревнования

    ## Changelog

    ### 2.0.0

    * <font color="red">**Breaking!**</font> Ресурс `accounts` переименован в `athletes` - [GET /integration/judge-bot/v1/athletes](#operations-athletes-getAthletes)
    * <font color="red">**Breaking!**</font> [GET /integration/judge-bot/v1/athletes](#operations-athletes-getAthletes) - изменен формат списка дисциплин, для командных дисциплин добавлен идентификатор команды
    * [GET /integration/judge-bot/v1/disciplines](#operations-disciplines-getDisciplines) - добавился тип результатов "Место"
    * [POST /integration/judge-bot/v1/results](#operations-results-createResult) - добавился тип результатов "Место"

    <details>

    <summary>Предыдущие версии</summary>

    ### 1.0.0

    * Добавлен ресурс API divisions
    * Добавлен ресурс API disciplines
    * Добавлен ресурс API accounts
    * Добавлен ресурс API results

    </details>

security:
  - basic: []

paths:

  /integration/judge-bot/v1/divisions:
    get:
      summary: Получение списка филиалов
      tags:
        - divisions
      operationId: getDivisions
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: ObjectId филиала
                        name:
                          type: string
                          description: Название филиала
                      required:
                        - id
                        - name
                required:
                  - items
              example:
                items:
                  - id: "507f1f77bcf86cd799439011"
                    name: "Центральный филиал"
                  - id: "507f1f77bcf86cd799439012"
                    name: "Восточный филиал"
        '401':
          $ref: '#/components/responses/AuthenticationError'

  /integration/judge-bot/v1/disciplines:
    get:
      summary: Получение списка спортивных дисциплин
      tags:
        - disciplines
      operationId: getDisciplines
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Discipline'
                required:
                  - items
              example:
                items:
                  - id: "507f1f77bcf86cd799439011"
                    name: "Мини-Футбол"
                    isTournament: true
                    isTeam: true
                    categories: []
                    resultType: points
                    tournament:
                      - stage: 1/4
                        competitions:
                          - id: 68000ff8fa9fb49584df8000
                            status: ended
                            participants:
                              - id: 507f1f77bcf86cd799439014
                                name: Белгород
                                divisionId: 507f1f77bcf86cd799439015
                                athlets:
                                  - id: 1
                                    firstName: Иван
                                    lastName: Иванов
                                    middleName: Иванович
                                    divisionId: 507f1f77bcf86cd799439016
                              - id: 507f1f77bcf86cd799439017
                                name: Воронеж
                                divisionId: 507f1f77bcf86cd799439018
                                athlets:
                                  - id: 2
                                    firstName: Петр
                                    lastName: Петров
                                    middleName: Петрович
                                    divisionId: 507f1f77bcf86cd799439019
                      - stage: 1/2
                        competitions:
                          - id: 68000ff8fa9fb49584df8001
                            status: ongoing
                            participants:
                              - id: 507f1f77bcf86cd799439014
                                name: Белгород
                                divisionId: 507f1f77bcf86cd799439015
                                athlets:
                                  - id: 1
                                    firstName: Иван
                                    lastName: Иванов
                                    middleName: Иванович
                                    divisionId: 507f1f77bcf86cd799439016
                              - id: 507f1f77bcf86cd799439017
                                name: Воронеж
                                divisionId: 507f1f77bcf86cd799439018
                                athlets:
                                  - id: 2
                                    firstName: Петр
                                    lastName: Петров
                                    middleName: Петрович
                                    divisionId: 507f1f77bcf86cd799439019
                          - id: 68000ff8fa9fb49584df8002
                            status: planned
                            participants:
                              - id: 507f1f77bcf86cd799439014
                                name: Белгород
                                divisionId: 507f1f77bcf86cd799439015
                                athlets:
                                  - id: 1
                                    firstName: Иван
                                    lastName: Иванов
                                    middleName: Иванович
                                    divisionId: 507f1f77bcf86cd799439016
                              - id: 507f1f77bcf86cd799439017
                                name: Воронеж
                                divisionId: 507f1f77bcf86cd799439018
                                athlets:
                                  - id: 2
                                    firstName: Петр
                                    lastName: Петров
                                    middleName: Петрович
                                    divisionId: 507f1f77bcf86cd799439019
                      - stage: Финал
                        competitions:
                          - id: 68000ff8fa9fb49584df8003
                            status: upcoming
                            participants:
                              - id: 507f1f77bcf86cd799439014
                                name: Белгород
                                divisionId: 507f1f77bcf86cd799439015
                                athlets:
                                  - id: 1
                                    firstName: Иван
                                    lastName: Иванов
                                    middleName: Иванович
                                    divisionId: 507f1f77bcf86cd799439016
                              - {}
                  - id: "507f1f77bcf86cd799439012"
                    name: "Дартс"
                    isTournament: false
                    isTeam: false
                    limit: 3
                    categories:
                      - title: Мужчины
                      - title: Женщины
                    resultType: points
                    competition:
                      id: 68000ff8fa9fb49584df8003
                      status: ended
                      participants:
                        - id: 1
                          firstName: Иван
                          lastName: Иванов
                          middleName: Иванович
                          divisionId: 507f1f77bcf86cd799439016
                        - id: 2
                          firstName: Иван
                          lastName: Иванов
                          middleName: Иванович
                          divisionId: 507f1f77bcf86cd799439017
                  - id: "507f1f77bcf86cd799439013"
                    name: "Бег 100м"
                    isTournament: false
                    isTeam: false
                    categories:
                      - title: Мужчины, 18-34 года
                        gender: male
                        age:
                          from: null
                          to: 34
                      - title: Мужчины, 35-49 лет
                        gender: male
                        age:
                          from: 35
                          to: null
                      - title: Женщины, 18-34 года
                        gender: female
                        age:
                          from: 18
                          to: 34
                      - title: Женщины, 35-49 лет
                        gender: female
                        age:
                          from: 35
                          to: 49
                    resultType: time
                    competition:
                      id: 68000ff8fa9fb49584df8003
                      status: planned
                      participants: []
                  - id: "507f1f77bcf86cd799439014"
                    name: "Бег 1000м"
                    isTournament: false
                    isTeam: false
                    categories:
                      - title: Мужчины, 18-34 года
                        gender: male
                        age:
                          from: 18
                          to: 34
                      - title: Мужчины, 35-49 лет
                        gender: male
                        age:
                          from: 35
                          to: 49
                    resultType: time
                    competition:
                      id: 68000ff8fa9fb49584df8003
                      status: planned
                      participants: []
                  - id: "507f1f77bcf86cd799439015"
                    name: "Эстафета"
                    isTournament: false
                    isTeam: true
                    limit: 4
                    categories: []
                    resultType: time
                    competition:
                      id: 68000ff8fa9fb49584df8003
                      status: planned
                      participants: []
        '401':
          $ref: '#/components/responses/AuthenticationError'

  /integration/judge-bot/v1/athletes:
    get:
      tags:
        - athletes
      operationId: getAthletes
      summary: Получение данных спортсменов
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                required:
                  - items
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      required:
                        - id
                      properties:
                        id:
                          type: integer
                          example: 1
                        firstName:
                          type: string
                          maxLength: 50
                        lastName:
                          type: string
                          maxLength: 50
                        middleName:
                          type: string
                          maxLength: 50
                        birthDate:
                          description: Дата рождения, формат даты ISO. Обязательно для спортсмена. Используется для вычисления возрастной категории
                          type: string
                          format: date
                          example: '1970-01-01'
                        weight:
                          description: Вес в кг. Обязательно для спортсмена. Используется для вычисления весовой категории
                          type: number
                        gender:
                          description: Пол. Обязательно для спортсмена
                          type: string
                          enum:
                            - male
                            - female
                        divisionId:
                          type: string
                          format: objectId
                        disciplines:
                          type: array
                          items:
                            type: object
                            required:
                              - id
                            properties:
                              id:
                                description: Идентификатор дисциплины
                                type: string
                                format: objectId
                              teamId:
                                description: Идентификатор команды для командных дисциплин
                                type: string
                                format: objectId
              examples:
                athlete:
                  description: Зарегистрированный спортсмен
                  value:
                    items:
                      - id: 3
                        firstName: Иван
                        lastName: Иванов
                        middleName: Иванович
                        birthDate: '2000-12-31'
                        gender: male
                        weight: 84
                        divisionId: '507f1f77bcf86cd799439012'
                        disciplines:
                          - '507f1f77bcf86cd799439013'
                          - '507f1f77bcf86cd799439014'
        '401':
          $ref: '#/components/responses/AuthenticationError'

  /integration/judge-bot/v1/results:
    post:
      tags:
        - results
      operationId: createResult
      summary: Отправка результатов спортивного события
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                correlationId:
                  type: string
                  description: Идентификатор пакета результатов. Можно любой рандомный уникальный, например GUID. Будет использоваться для предотвращения повторной обработки одного и того же запроса
                competitionId:
                  type: string
                  description: Идентификатор соревнования
                results:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    oneOf:
                      - required:
                          - athleteId
                          - result
                        properties:
                          athleteId:
                            type: number
                            description: Идентификатор спортсмена
                          result:
                            $ref: '#/components/schemas/Result'
                      - required:
                          - teamId
                          - result
                        properties:
                          athleteId:
                            type: string
                            description: Идентификатор команды
                          result:
                            $ref: '#/components/schemas/Result'
              additionalProperties: false
            example:
              correlationId: "3d7bc6c4-72d2-4d01-9db6-d2d4910b2fb7"
              competitionId: "507f1f77bcf86cd799439014"
              results:
                - athleteId: 1
                  result: 10000
                - athleteId: 2
                  result: 12000
      responses:
        '204':
          description: Успешный ответ
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/AuthenticationError'

components:
  responses:
    BadRequestError:
      description: Ошибка валидации
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            errorName: BadRequestError
            error: Invalid input data
            userMessage: Некорректные данные
    AuthenticationError:
      description: Ошибка авторизации
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            errorName: AuthenticationError
            error: Unauthorized
            userMessage: Ошибка авторизации
  schemas:
    Error:
      type: object
      properties:
        errorName:
          type: string
        error:
          type: string
        userMessage:
          type: string

    Category:
      type: object
      description: |
        Описание категории участников, по которой будет происходить зачет.
      required:
        - title
      properties:
        title:
          type: string
          description: Навзание возрастной категории для отображения
        gender:
          type: string
          description: Пол участника
          enum: ['male', 'female']
        age:
          type: object
          description: Возраст - от и до. Обе границы опциональны, но одна обязательно будет
          required:
            - from
            - to
          properties:
            from:
              type: number
              nullable: true
            to:
              type: number
              nullable: true
        weight:
          type: object
          description: Вес в кг - от и до. Обе границы опциональны, но одна обязательно будет
          required:
            - from
            - to
          properties:
            from:
              type: number
              nullable: true
            to:
              type: number
              nullable: true

    Discipline:
      type: object
      description: Спортивная дисциплина
      oneOf:
        - required:
          - id
          - name
          - type
          - isTournament
          - isTeam
          - categories
          - resultType
          - competition
        - required:
          - id
          - name
          - type
          - isTournament
          - isTeam
          - categories
          - resultType
          - tournament
      properties:
        id:
          type: string
          description: Идентификатор
          format: ObjectId
        name:
          type: string
          description: Название дисциплины
        type:
          type: string
          description: Вид дисциплины
        isTournament:
          type: boolean
          description: Турнирная дисциплина
        isTeam:
          type: boolean
          description: Тип участия, командная или индивидиуальная дисциплина
        categories:
          type: array
          description: Категории участников, выступающих в дисциплинах. Пустой, если для дисциплины предусмотрен только общий зачет
          minItems: 0
          items:
            $ref: '#/components/schemas/Category'
        limit:
          type: integer
          minimum: 1
          description: Размер команды или количество участников от филиала
        resultType:
          type: string
          description: Тип результатов соревнований по дисциплине
          enum:
            - points
            - time
            - win-lose
            - place
        competition:
          $ref: '#/components/schemas/Competition'
        tournament:
          $ref: '#/components/schemas/Tournament'

    Athlete:
      type: object
      required:
        - id
        - firstName
        - lastName
        - middleName
        - divisionId
      properties:
        id:
          type: integer
          description: Идентификатор аккаунта
          minimum: 1
        firstName:
          type: string
          description: Имя
          maxLength: 50
        lastName:
          type: string
          description: Фамилия
          maxLength: 50
        middleName:
          type: string
          description: Отчество
          maxLength: 50
        divisionId:
          type: string
          description: Идентификатор филиала
          format: ObjectId

    Team:
      type: object
      required:
        - id
        - name
        - divisionId
        - athletes
      properties:
        id:
          type: string
          description: Идентификатор
          format: ObjectId
        name:
          type: string
          description: Название
        divisionId:
          type: string
          description: Идентификатор филиала
          format: ObjectId
        athlets:
          type: array
          items:
            $ref: '#/components/schemas/Athlete'

    PointsResult:
      description: Результат соревнования в очках
      type: number
      minimum: 0
      nullable: true
    TimeResult:
      description: Результат соревнования по времени. Значение в мс
      type: number
      minimum: 0
      nullable: true
    WinLoseResult:
      description: Результат соревнования на победу
      type: string
      enum:
        - win
        - lose
      nullable: true
    PlaceResult:
      description: Результат в соревнованиях по рейтингу
      type: number
      minimum: 0
      nullable: true
    Result:
      oneOf:
        - $ref: '#/components/schemas/PointsResult'
        - $ref: '#/components/schemas/TimeResult'
        - $ref: '#/components/schemas/WinLoseResult'
        - $ref: '#/components/schemas/PlaceResult'

    Competition:
      type: object
      required:
        - id
        - status
        - participants
      properties:
        id:
          type: string
          description: Идентификатор соревнования
          format: ObjectId
        status:
          type: string
          description: |
            Статус результатов по соревнованию:
            - planned - запланировано, но состав ещё не определён
            - upcoming - соревнование ожидает начала
            - ongoing - соревнование идёт
            - ended - соревнование завершено
        participants:
          type: array
          minItems: 0
          items:
            oneOf:
              - $ref: '#/components/schemas/Athlete'
              - $ref: '#/components/schemas/Team'

    Tournament:
      description: Результаты турнира
      type: array
      minItems: 0
      items:
        type: object
        required:
          - stage
          - competitions
        properties:
          stage:
            description: Название этапа турнира - 1/8, 1/4 и т.д.
            type: string
          competitions:
            type: array
            minItems: 0
            items:
              $ref: '#/components/schemas/Competition'
